# $Header: /space/home/eng/cjm/cvs/libdprt-frodospec/Makefile.common,v 1.1 2025-02-10 11:12:13 cjm Exp $

FRODOSPEC_HOME			= frodospec
LIBDPRT_FRODOSPEC_SRC_HOME	= $(LIBDPRT_SRC_HOME)/$(FRODOSPEC_HOME)
LIBDPRT_FRODOSPEC_BIN_HOME	= $(LIBDPRT_BIN_HOME)/$(FRODOSPEC_HOME)
LIBDPRT_FRODOSPEC_DOC_HOME	= $(LIBDPRT_DOC_HOME)/$(FRODOSPEC_HOME)

#
# $Log: not supported by cvs2svn $
#
